// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhbafbeoiafmpnedqtjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxoYmFmYmVvaWFmbXBuZWRxdGptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MTg5MTUsImV4cCI6MjA2NTQ5NDkxNX0.502EQ1XiYRASPzKT03Dpo_4Bttxh1QxwGMIMjhvQ5EI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);